<#
.SYNOPSIS
    RTX Core Framework — One-Click Sync Script (Windows)
    https://github.com/PsProsen-Dev/RTXCoreFramework

.DESCRIPTION
    Run this script AFTER you have your personalized RTX framework file ready
    (generated by your AI agent during initialization). It will copy your
    personalized framework into all known AI tool config locations on Windows.

.USAGE
    1. Save your personalized framework as: %USERPROFILE%\RTXCoreFramework.md
    2. Open PowerShell and run: .\sync.ps1
    3. Done! All your tools are now synced.
#>

$ErrorActionPreference = "Stop"

# ── Source File ──────────────────────────────────────────────────────────────
$sourceFile = "$env:USERPROFILE\RTXCoreFramework.md"

if (-not (Test-Path $sourceFile)) {
    Write-Host ""
    Write-Host "❌ ERROR: Personalized framework not found at:" -ForegroundColor Red
    Write-Host "   $sourceFile" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "👉 Run the First-Boot Protocol in any AI agent first to generate your" -ForegroundColor Cyan
    Write-Host "   personalized framework, then save it to the path above and re-run." -ForegroundColor Cyan
    exit 1
}

Write-Host ""
Write-Host "⚡ RTX Core Framework — One-Click Sync Script" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "📂 Source: $sourceFile" -ForegroundColor Cyan
Write-Host ""

# ── Target Locations ─────────────────────────────────────────────────────────
$targets = @(
    @{ Label = "Gemini";         Path = "$env:USERPROFILE\.gemini\GEMINI.md" },
    @{ Label = "Codex CLI";      Path = "$env:USERPROFILE\.codex\AGENTS.md" },
    @{ Label = "Claude";         Path = "$env:USERPROFILE\CLAUDE.md" },
    @{ Label = "AGENTS fallback";Path = "$env:USERPROFILE\AGENTS.md" },
    @{ Label = "Cursor";         Path = "$env:USERPROFILE\.cursor\rules\RTXCoreFramework.mdc" },
    @{ Label = "Copilot (VS)";   Path = "$env:APPDATA\Code\User\copilot-instructions.md" }
)

$synced = 0
$failed = 0

foreach ($target in $targets) {
    try {
        $dir = Split-Path $target.Path -Parent
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
        }
        Copy-Item -Path $sourceFile -Destination $target.Path -Force
        Write-Host "  ✅ $($target.Label.PadRight(18)) → $($target.Path)" -ForegroundColor Green
        $synced++
    } catch {
        Write-Host "  ⚠️  $($target.Label.PadRight(18)) → FAILED: $($_.Exception.Message)" -ForegroundColor Yellow
        $failed++
    }
}

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "✅ Synced: $synced tool(s)   ⚠️  Skipped: $failed tool(s)" -ForegroundColor White
Write-Host ""
Write-Host "🚀 RTX Sync complete! Restart your AI tools to apply the new framework." -ForegroundColor Yellow
Write-Host ""
